#!/bin/bash

#
##
#

show_info(){
	echo "[  UpdatePythonPackages  ] $1"
}

finish_program(){
	show_info "Finishing program..."
	exit $1
}

show_error(){
	echo "[  Error  ] $(tput setaf 1)$1$(tput sgr0)"
}

#
##
#

# Verify if PIP is installed
if ! (which pip) > /dev/null 2>&1
then
	show_error "PIP was not found"
	finish_program 1
fi

# Get installed packages
PACKAGES=$(pip3 list | awk '{print $1}' | sed '1d;2d')
PACKAGES_NUMBER=$(pip3 list | awk '{print $1}' | sed '1d;2d' | wc -l)
show_info "$PACKAGES_NUMBER packages were found."

# Control variable
i=1

# Upgrade packages
for package in $PACKAGES
do
	echo ""
	show_info "$(tput setaf 2)Updating $package$(tput sgr0) $(tput setaf 4)($i out of $PACKAGES_NUMBER)$(tput sgr0)"
	pip install --upgrade $package
	if [ ! $? -eq 0 ]
	then
		show_error "An error occurred when trying to update $package package"
	fi
	((i++))
done

finish_program 0
