#!/bin/bash

# Configuration variables
OUTPUT_FILE='requirements.txt'

#
##
#

show_info(){
	echo "[  UpdatePythonPackages  ] $1"
}

finish_program(){
	show_info "Finishing program..."
	exit $1
}

#
##
#

# Verify if PIP is installed
if ! (which pip) > /dev/null 2>&1
then
	show_info "PIP was not found"
	finish_program 1
fi

# Upgrade pip package
show_info "Upgrading PIP"
python3 -m pip install --upgrade pip

# Redirect the list of installed packages to a file in the current working directory
show_info "Writing a list of installed packages to $OUTPUT_FILE"
pip freeze > $OUTPUT_FILE

# Replace the '==' with '>='
sed -i 's/==/>=/g' $OUTPUT_FILE

# Update all packages in the file
show_info "Updating Python packages"
pip install -r $OUTPUT_FILE --upgrade

# Delete output file
rm $OUTPUT_FILE

finish_program 0
